BEGIN TRANSACTION;
DROP TABLE IF EXISTS "LogFiles";
CREATE TABLE IF NOT EXISTS "LogFiles" (
	"id"	INTEGER NOT NULL,
	"Name"	TEXT NOT NULL DEFAULT 'Log-Doe',
	"LogDate"	TEXT DEFAULT 0,
	"ImportDate"	TEXT NOT NULL DEFAULT 0,
	"UUID"	TEXT DEFAULT '00000000-0000-0000-0000-000000000000',
	"Version"	TEXT DEFAULT '0.0',
	"LinesNb"	INTEGER DEFAULT 0,
	"Size"	INTEGER DEFAULT 0,
	"Content"	BLOB,
	"FramesExtracted"	BOOLEAN NOT NULL DEFAULT 0,
	"SecuredFramesExtracted"	BOOLEAN NOT NULL DEFAULT 0,
	PRIMARY KEY("id" AUTOINCREMENT),
	UNIQUE("id")
);
DROP TABLE IF EXISTS "SecuredFrames";
CREATE TABLE IF NOT EXISTS "SecuredFrames" (
	"id"	INTEGER NOT NULL,
	"Name"	TEXT NOT NULL,
	"TimeStamp"	TEXT NOT NULL,
	"FrameId"	INTEGER NOT NULL,
	"tMAC"	TEXT,
	"Payload"	TEXT,
	"FV"	TEXT,
	"Pad"	TEXT,
        "Mac"   TEXT DEFAULT 'unknown' NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT),
	UNIQUE("id")
);
DROP TABLE IF EXISTS "MACProvFrames";
CREATE TABLE IF NOT EXISTS "MACProvFrames" (
	"id"	INTEGER NOT NULL,
	"LogFileId"	INTEGER,
	"Frame"	TEXT,
	"SHECmdExtracted"	BOOLEAN NOT NULL DEFAULT 0,
	PRIMARY KEY("id" AUTOINCREMENT),
	UNIQUE("id"),
	FOREIGN KEY("LogFileId") REFERENCES "LogFiles"("id")
);
DROP TABLE IF EXISTS "SHEArgsPackets";
CREATE TABLE IF NOT EXISTS "SHEArgsPackets" (
	"id"	INTEGER NOT NULL,
	"MACProvFrameId"	INTEGER,
	"M2"	TEXT,
	"KeysExtracted"	BOOLEAN NOT NULL DEFAULT 0,
	PRIMARY KEY("id" AUTOINCREMENT),
	FOREIGN KEY("MACProvFrameId") REFERENCES "MACProvFrames"("id"),
	UNIQUE("id")
);
DROP TABLE IF EXISTS "MACKeys";
CREATE TABLE IF NOT EXISTS "MACKeys" (
	"id"	INTEGER NOT NULL,
	"MACProvFrameId"	INTEGER,
	"MacKey"	TEXT,
	"cid"	TEXT,
	"fid"	TEXT,
	"IsMaster"	BOOLEAN NOT NULL DEFAULT 0,
	UNIQUE("id"),
	PRIMARY KEY("id" AUTOINCREMENT)
);
DROP TABLE IF EXISTS "ActiveKeys";
CREATE TABLE IF NOT EXISTS "ActiveKeys" (
	"id"	INTEGER NOT NULL,
	"MacEcu"	TEXT,
	"MasterEcu"	TEXT,
	UNIQUE("id"),
	PRIMARY KEY("id" AUTOINCREMENT)
);
DROP TABLE IF EXISTS "ECUs";
CREATE TABLE IF NOT EXISTS "ECUs" (
	"id"	INTEGER NOT NULL,
	"Name"	TEXT,
	"IsDomainMaster"	BOOLEAN NOT NULL,
	"DomainMasterId"	INTEGER,
	PRIMARY KEY("id" AUTOINCREMENT),
	UNIQUE("id")
);
INSERT INTO "ECUs" ("id","Name","IsDomainMaster","DomainMasterId") VALUES (1,'ADAS',1,1),
 (2,'FRCAMERA',0,1),
 (3,'SONAR',0,1),
 (4,'ACU',0,5),
 (5,'BCM',1,5),
 (6,'BMS12V',0,5),
 (7,'HFM',0,5),
 (8,'HVAC',0,5),
 (9,'METER',0,5),
 (10,'USM',0,5),
 (11,'CDM',1,11),
 (12,'EPKB',0,11),
 (13,'EPS',0,11),
 (14,'STRG',0,11),
 (15,'VDC',0,11),
 (16,'ATCU',0,17),
 (17,'ECM',1,17),
 (18,'PWT',1,17),
 (19,'HEVC',1,19);
COMMIT;
